### ISSUE TITLE
[BUG] BOLs from sheet are not downloading

### ISSUE THREAD

**Issue by RyanHypeMill** [azizultex/jitsi-meet-test#4]
When I go on the Google sheet to download a BOL it is sending me to the hub but not downloading the BOL. Not sure if this will fix itself when we push live or not.

**Comment by ImtiazEpu** [comment]
@RyanHypeMill, please add this issue to the hoodslyhub Repository.

**Comment by ImtiazEpu** [comment]
@RyanHypeMill, please add this issue to the hoodslyhub Repository.

**Comment by ImtiazEpu** [comment]
@RyanHypeMill, please add this issue to the hoodslyhub Repository.

**Comment by ImtiazEpu** [comment]
@RyanHypeMill, please add this issue to the hoodslyhub Repository.

**Comment by ImtiazEpu** [comment]
@RyanHypeMill All new orders will correctly generate BOL/shipping labels and can also download correctly from the WRH sheet. Please check & let us know.
